<?php
/**
 * ColorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GroupDocs\Comparison
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GroupDocs\Comparison;

/**
 * ColorTest Class Doc Comment
 *
 * @category    Class */
// * @description Color
/**
 * @package     GroupDocs\Comparison
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ColorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Color"
     */
    public function testColor()
    {
    }

    /**
     * Test attribute "transparent"
     */
    public function testPropertyTransparent()
    {
    }

    /**
     * Test attribute "aliceBlue"
     */
    public function testPropertyAliceBlue()
    {
    }

    /**
     * Test attribute "antiqueWhite"
     */
    public function testPropertyAntiqueWhite()
    {
    }

    /**
     * Test attribute "aqua"
     */
    public function testPropertyAqua()
    {
    }

    /**
     * Test attribute "aquamarine"
     */
    public function testPropertyAquamarine()
    {
    }

    /**
     * Test attribute "azure"
     */
    public function testPropertyAzure()
    {
    }

    /**
     * Test attribute "beige"
     */
    public function testPropertyBeige()
    {
    }

    /**
     * Test attribute "bisque"
     */
    public function testPropertyBisque()
    {
    }

    /**
     * Test attribute "black"
     */
    public function testPropertyBlack()
    {
    }

    /**
     * Test attribute "blanchedAlmond"
     */
    public function testPropertyBlanchedAlmond()
    {
    }

    /**
     * Test attribute "blue"
     */
    public function testPropertyBlue()
    {
    }

    /**
     * Test attribute "blueViolet"
     */
    public function testPropertyBlueViolet()
    {
    }

    /**
     * Test attribute "brown"
     */
    public function testPropertyBrown()
    {
    }

    /**
     * Test attribute "burlyWood"
     */
    public function testPropertyBurlyWood()
    {
    }

    /**
     * Test attribute "cadetBlue"
     */
    public function testPropertyCadetBlue()
    {
    }

    /**
     * Test attribute "chartreuse"
     */
    public function testPropertyChartreuse()
    {
    }

    /**
     * Test attribute "chocolate"
     */
    public function testPropertyChocolate()
    {
    }

    /**
     * Test attribute "coral"
     */
    public function testPropertyCoral()
    {
    }

    /**
     * Test attribute "cornflowerBlue"
     */
    public function testPropertyCornflowerBlue()
    {
    }

    /**
     * Test attribute "cornsilk"
     */
    public function testPropertyCornsilk()
    {
    }

    /**
     * Test attribute "crimson"
     */
    public function testPropertyCrimson()
    {
    }

    /**
     * Test attribute "cyan"
     */
    public function testPropertyCyan()
    {
    }

    /**
     * Test attribute "darkBlue"
     */
    public function testPropertyDarkBlue()
    {
    }

    /**
     * Test attribute "darkCyan"
     */
    public function testPropertyDarkCyan()
    {
    }

    /**
     * Test attribute "darkGoldenrod"
     */
    public function testPropertyDarkGoldenrod()
    {
    }

    /**
     * Test attribute "darkGray"
     */
    public function testPropertyDarkGray()
    {
    }

    /**
     * Test attribute "darkGreen"
     */
    public function testPropertyDarkGreen()
    {
    }

    /**
     * Test attribute "darkKhaki"
     */
    public function testPropertyDarkKhaki()
    {
    }

    /**
     * Test attribute "darkMagenta"
     */
    public function testPropertyDarkMagenta()
    {
    }

    /**
     * Test attribute "darkOliveGreen"
     */
    public function testPropertyDarkOliveGreen()
    {
    }

    /**
     * Test attribute "darkOrange"
     */
    public function testPropertyDarkOrange()
    {
    }

    /**
     * Test attribute "darkOrchid"
     */
    public function testPropertyDarkOrchid()
    {
    }

    /**
     * Test attribute "darkRed"
     */
    public function testPropertyDarkRed()
    {
    }

    /**
     * Test attribute "darkSalmon"
     */
    public function testPropertyDarkSalmon()
    {
    }

    /**
     * Test attribute "darkSeaGreen"
     */
    public function testPropertyDarkSeaGreen()
    {
    }

    /**
     * Test attribute "darkSlateBlue"
     */
    public function testPropertyDarkSlateBlue()
    {
    }

    /**
     * Test attribute "darkSlateGray"
     */
    public function testPropertyDarkSlateGray()
    {
    }

    /**
     * Test attribute "darkTurquoise"
     */
    public function testPropertyDarkTurquoise()
    {
    }

    /**
     * Test attribute "darkViolet"
     */
    public function testPropertyDarkViolet()
    {
    }

    /**
     * Test attribute "deepPink"
     */
    public function testPropertyDeepPink()
    {
    }

    /**
     * Test attribute "deepSkyBlue"
     */
    public function testPropertyDeepSkyBlue()
    {
    }

    /**
     * Test attribute "dimGray"
     */
    public function testPropertyDimGray()
    {
    }

    /**
     * Test attribute "dodgerBlue"
     */
    public function testPropertyDodgerBlue()
    {
    }

    /**
     * Test attribute "firebrick"
     */
    public function testPropertyFirebrick()
    {
    }

    /**
     * Test attribute "floralWhite"
     */
    public function testPropertyFloralWhite()
    {
    }

    /**
     * Test attribute "forestGreen"
     */
    public function testPropertyForestGreen()
    {
    }

    /**
     * Test attribute "fuchsia"
     */
    public function testPropertyFuchsia()
    {
    }

    /**
     * Test attribute "gainsboro"
     */
    public function testPropertyGainsboro()
    {
    }

    /**
     * Test attribute "ghostWhite"
     */
    public function testPropertyGhostWhite()
    {
    }

    /**
     * Test attribute "gold"
     */
    public function testPropertyGold()
    {
    }

    /**
     * Test attribute "goldenrod"
     */
    public function testPropertyGoldenrod()
    {
    }

    /**
     * Test attribute "gray"
     */
    public function testPropertyGray()
    {
    }

    /**
     * Test attribute "green"
     */
    public function testPropertyGreen()
    {
    }

    /**
     * Test attribute "greenYellow"
     */
    public function testPropertyGreenYellow()
    {
    }

    /**
     * Test attribute "honeydew"
     */
    public function testPropertyHoneydew()
    {
    }

    /**
     * Test attribute "hotPink"
     */
    public function testPropertyHotPink()
    {
    }

    /**
     * Test attribute "indianRed"
     */
    public function testPropertyIndianRed()
    {
    }

    /**
     * Test attribute "indigo"
     */
    public function testPropertyIndigo()
    {
    }

    /**
     * Test attribute "ivory"
     */
    public function testPropertyIvory()
    {
    }

    /**
     * Test attribute "khaki"
     */
    public function testPropertyKhaki()
    {
    }

    /**
     * Test attribute "lavender"
     */
    public function testPropertyLavender()
    {
    }

    /**
     * Test attribute "lavenderBlush"
     */
    public function testPropertyLavenderBlush()
    {
    }

    /**
     * Test attribute "lawnGreen"
     */
    public function testPropertyLawnGreen()
    {
    }

    /**
     * Test attribute "lemonChiffon"
     */
    public function testPropertyLemonChiffon()
    {
    }

    /**
     * Test attribute "lightBlue"
     */
    public function testPropertyLightBlue()
    {
    }

    /**
     * Test attribute "lightCoral"
     */
    public function testPropertyLightCoral()
    {
    }

    /**
     * Test attribute "lightCyan"
     */
    public function testPropertyLightCyan()
    {
    }

    /**
     * Test attribute "lightGoldenrodYellow"
     */
    public function testPropertyLightGoldenrodYellow()
    {
    }

    /**
     * Test attribute "lightGreen"
     */
    public function testPropertyLightGreen()
    {
    }

    /**
     * Test attribute "lightGray"
     */
    public function testPropertyLightGray()
    {
    }

    /**
     * Test attribute "lightPink"
     */
    public function testPropertyLightPink()
    {
    }

    /**
     * Test attribute "lightSalmon"
     */
    public function testPropertyLightSalmon()
    {
    }

    /**
     * Test attribute "lightSeaGreen"
     */
    public function testPropertyLightSeaGreen()
    {
    }

    /**
     * Test attribute "lightSkyBlue"
     */
    public function testPropertyLightSkyBlue()
    {
    }

    /**
     * Test attribute "lightSlateGray"
     */
    public function testPropertyLightSlateGray()
    {
    }

    /**
     * Test attribute "lightSteelBlue"
     */
    public function testPropertyLightSteelBlue()
    {
    }

    /**
     * Test attribute "lightYellow"
     */
    public function testPropertyLightYellow()
    {
    }

    /**
     * Test attribute "lime"
     */
    public function testPropertyLime()
    {
    }

    /**
     * Test attribute "limeGreen"
     */
    public function testPropertyLimeGreen()
    {
    }

    /**
     * Test attribute "linen"
     */
    public function testPropertyLinen()
    {
    }

    /**
     * Test attribute "magenta"
     */
    public function testPropertyMagenta()
    {
    }

    /**
     * Test attribute "maroon"
     */
    public function testPropertyMaroon()
    {
    }

    /**
     * Test attribute "mediumAquamarine"
     */
    public function testPropertyMediumAquamarine()
    {
    }

    /**
     * Test attribute "mediumBlue"
     */
    public function testPropertyMediumBlue()
    {
    }

    /**
     * Test attribute "mediumOrchid"
     */
    public function testPropertyMediumOrchid()
    {
    }

    /**
     * Test attribute "mediumPurple"
     */
    public function testPropertyMediumPurple()
    {
    }

    /**
     * Test attribute "mediumSeaGreen"
     */
    public function testPropertyMediumSeaGreen()
    {
    }

    /**
     * Test attribute "mediumSlateBlue"
     */
    public function testPropertyMediumSlateBlue()
    {
    }

    /**
     * Test attribute "mediumSpringGreen"
     */
    public function testPropertyMediumSpringGreen()
    {
    }

    /**
     * Test attribute "mediumTurquoise"
     */
    public function testPropertyMediumTurquoise()
    {
    }

    /**
     * Test attribute "mediumVioletRed"
     */
    public function testPropertyMediumVioletRed()
    {
    }

    /**
     * Test attribute "midnightBlue"
     */
    public function testPropertyMidnightBlue()
    {
    }

    /**
     * Test attribute "mintCream"
     */
    public function testPropertyMintCream()
    {
    }

    /**
     * Test attribute "mistyRose"
     */
    public function testPropertyMistyRose()
    {
    }

    /**
     * Test attribute "moccasin"
     */
    public function testPropertyMoccasin()
    {
    }

    /**
     * Test attribute "navajoWhite"
     */
    public function testPropertyNavajoWhite()
    {
    }

    /**
     * Test attribute "navy"
     */
    public function testPropertyNavy()
    {
    }

    /**
     * Test attribute "oldLace"
     */
    public function testPropertyOldLace()
    {
    }

    /**
     * Test attribute "olive"
     */
    public function testPropertyOlive()
    {
    }

    /**
     * Test attribute "oliveDrab"
     */
    public function testPropertyOliveDrab()
    {
    }

    /**
     * Test attribute "orange"
     */
    public function testPropertyOrange()
    {
    }

    /**
     * Test attribute "orangeRed"
     */
    public function testPropertyOrangeRed()
    {
    }

    /**
     * Test attribute "orchid"
     */
    public function testPropertyOrchid()
    {
    }

    /**
     * Test attribute "paleGoldenrod"
     */
    public function testPropertyPaleGoldenrod()
    {
    }

    /**
     * Test attribute "paleGreen"
     */
    public function testPropertyPaleGreen()
    {
    }

    /**
     * Test attribute "paleTurquoise"
     */
    public function testPropertyPaleTurquoise()
    {
    }

    /**
     * Test attribute "paleVioletRed"
     */
    public function testPropertyPaleVioletRed()
    {
    }

    /**
     * Test attribute "papayaWhip"
     */
    public function testPropertyPapayaWhip()
    {
    }

    /**
     * Test attribute "peachPuff"
     */
    public function testPropertyPeachPuff()
    {
    }

    /**
     * Test attribute "peru"
     */
    public function testPropertyPeru()
    {
    }

    /**
     * Test attribute "pink"
     */
    public function testPropertyPink()
    {
    }

    /**
     * Test attribute "plum"
     */
    public function testPropertyPlum()
    {
    }

    /**
     * Test attribute "powderBlue"
     */
    public function testPropertyPowderBlue()
    {
    }

    /**
     * Test attribute "purple"
     */
    public function testPropertyPurple()
    {
    }

    /**
     * Test attribute "red"
     */
    public function testPropertyRed()
    {
    }

    /**
     * Test attribute "rosyBrown"
     */
    public function testPropertyRosyBrown()
    {
    }

    /**
     * Test attribute "royalBlue"
     */
    public function testPropertyRoyalBlue()
    {
    }

    /**
     * Test attribute "saddleBrown"
     */
    public function testPropertySaddleBrown()
    {
    }

    /**
     * Test attribute "salmon"
     */
    public function testPropertySalmon()
    {
    }

    /**
     * Test attribute "sandyBrown"
     */
    public function testPropertySandyBrown()
    {
    }

    /**
     * Test attribute "seaGreen"
     */
    public function testPropertySeaGreen()
    {
    }

    /**
     * Test attribute "seaShell"
     */
    public function testPropertySeaShell()
    {
    }

    /**
     * Test attribute "sienna"
     */
    public function testPropertySienna()
    {
    }

    /**
     * Test attribute "silver"
     */
    public function testPropertySilver()
    {
    }

    /**
     * Test attribute "skyBlue"
     */
    public function testPropertySkyBlue()
    {
    }

    /**
     * Test attribute "slateBlue"
     */
    public function testPropertySlateBlue()
    {
    }

    /**
     * Test attribute "slateGray"
     */
    public function testPropertySlateGray()
    {
    }

    /**
     * Test attribute "snow"
     */
    public function testPropertySnow()
    {
    }

    /**
     * Test attribute "springGreen"
     */
    public function testPropertySpringGreen()
    {
    }

    /**
     * Test attribute "steelBlue"
     */
    public function testPropertySteelBlue()
    {
    }

    /**
     * Test attribute "tan"
     */
    public function testPropertyTan()
    {
    }

    /**
     * Test attribute "teal"
     */
    public function testPropertyTeal()
    {
    }

    /**
     * Test attribute "thistle"
     */
    public function testPropertyThistle()
    {
    }

    /**
     * Test attribute "tomato"
     */
    public function testPropertyTomato()
    {
    }

    /**
     * Test attribute "turquoise"
     */
    public function testPropertyTurquoise()
    {
    }

    /**
     * Test attribute "violet"
     */
    public function testPropertyViolet()
    {
    }

    /**
     * Test attribute "wheat"
     */
    public function testPropertyWheat()
    {
    }

    /**
     * Test attribute "white"
     */
    public function testPropertyWhite()
    {
    }

    /**
     * Test attribute "whiteSmoke"
     */
    public function testPropertyWhiteSmoke()
    {
    }

    /**
     * Test attribute "yellow"
     */
    public function testPropertyYellow()
    {
    }

    /**
     * Test attribute "yellowGreen"
     */
    public function testPropertyYellowGreen()
    {
    }

    /**
     * Test attribute "r"
     */
    public function testPropertyR()
    {
    }

    /**
     * Test attribute "g"
     */
    public function testPropertyG()
    {
    }

    /**
     * Test attribute "b"
     */
    public function testPropertyB()
    {
    }

    /**
     * Test attribute "a"
     */
    public function testPropertyA()
    {
    }

    /**
     * Test attribute "isKnownColor"
     */
    public function testPropertyIsKnownColor()
    {
    }

    /**
     * Test attribute "isEmpty"
     */
    public function testPropertyIsEmpty()
    {
    }

    /**
     * Test attribute "isNamedColor"
     */
    public function testPropertyIsNamedColor()
    {
    }

    /**
     * Test attribute "isSystemColor"
     */
    public function testPropertyIsSystemColor()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "empty"
     */
    public function testPropertyEmpty()
    {
    }
}
