<?php
/**
 * ComparisonFileInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GroupDocs\Comparison
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GroupDocs\Comparison;

/**
 * ComparisonFileInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description ComparisonFileInfo dto
/**
 * @package     GroupDocs\Comparison
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ComparisonFileInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ComparisonFileInfo"
     */
    public function testComparisonFileInfo()
    {
    }

    /**
     * Test attribute "folder"
     */
    public function testPropertyFolder()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }
}
