<?php
/**
 * ComparisonRequestSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GroupDocs\Comparison
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GroupDocs.Comparison for Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GroupDocs\Comparison;

/**
 * ComparisonRequestSettingsTest Class Doc Comment
 *
 * @category    Class */
// * @description ComparisonRequestSettings dto
/**
 * @package     GroupDocs\Comparison
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ComparisonRequestSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ComparisonRequestSettings"
     */
    public function testComparisonRequestSettings()
    {
    }

    /**
     * Test attribute "generateSummaryPage"
     */
    public function testPropertyGenerateSummaryPage()
    {
    }

    /**
     * Test attribute "showDeletedContent"
     */
    public function testPropertyShowDeletedContent()
    {
    }

    /**
     * Test attribute "styleChangeDetection"
     */
    public function testPropertyStyleChangeDetection()
    {
    }

    /**
     * Test attribute "insertedItemsStyle"
     */
    public function testPropertyInsertedItemsStyle()
    {
    }

    /**
     * Test attribute "deletedItemsStyle"
     */
    public function testPropertyDeletedItemsStyle()
    {
    }

    /**
     * Test attribute "styleChangedItemsStyle"
     */
    public function testPropertyStyleChangedItemsStyle()
    {
    }

    /**
     * Test attribute "wordsSeparatorChars"
     */
    public function testPropertyWordsSeparatorChars()
    {
    }

    /**
     * Test attribute "useFramesForDelInsElements"
     */
    public function testPropertyUseFramesForDelInsElements()
    {
    }

    /**
     * Test attribute "detailLevel"
     */
    public function testPropertyDetailLevel()
    {
    }

    /**
     * Test attribute "calculateComponentCoordinates"
     */
    public function testPropertyCalculateComponentCoordinates()
    {
    }

    /**
     * Test attribute "cloneMetadata"
     */
    public function testPropertyCloneMetadata()
    {
    }

    /**
     * Test attribute "metaData"
     */
    public function testPropertyMetaData()
    {
    }

    /**
     * Test attribute "passwordSaveOption"
     */
    public function testPropertyPasswordSaveOption()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "markDeletedInsertedContentDeep"
     */
    public function testPropertyMarkDeletedInsertedContentDeep()
    {
    }
}
